# Listening address for the Taskflow API server
# You can change this to 0.0.0.0 to allow API access from external machines
# This can create security problems. USE WITH CAUTION
api_host: "localhost"

# Set the listen port for the API server
# api_port: 4305

# Set the amount of main memory to reserve when sheduling task
# reserved_memory_bytes: 100M

# Set the amount of memory to reserve for each GPU when scheduling tasks
# reserved_gpu_memory_bytes: 1M

# Set the number of seconds between each system query
# system_query_interval: 2
