Document: taskflow
Title: Debian taskflow Manual
Author: <insert document author here>
Abstract: This manual describes what taskflow is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/taskflow/taskflow.sgml.gz

Format: postscript
Files: /usr/share/doc/taskflow/taskflow.ps.gz

Format: text
Files: /usr/share/doc/taskflow/taskflow.text.gz

Format: HTML
Index: /usr/share/doc/taskflow/html/index.html
Files: /usr/share/doc/taskflow/html/*.html
